#required port
server.port: 5000

#external api config
proxy:
  name: SimilarProductProxy
  url: http://localhost:3001

#api config
api-config:
  version: "/api/v1"

#swagger config
springdoc:
  api-docs:
    path: /api-docs
